[package]
name = "jcbhmr/hello-world-go-wasmer-cli"
version = "1.0.1"
description = "👨‍💻 Example CLI application built with Go and distributed via Wasmer"
license = "0BSD"
readme = "./README.md"
repository = "https://github.com/jcbhmr/hello-world-go-wasmer-cli"
homepage = "https://github.com/jcbhmr/hello-world-go-wasmer-cli#readme"
entrypoint = "hello-world-go-wasmer-cli"

[[module]]
name = "hello-world-go-wasmer-cli"
source = "./out/hello-world-go-wasmer-cli.wasm"

[[command]]
name = "hello-world-go-wasmer-cli"
module = "hello-world-go-wasmer-cli"
runner = "wasi"
